[build]
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "dist/functions" 

[[redirects]]
  from = "/api/*"
  to = "/.functions/express/api/:splat"
  status = 200